spring:
  application:
    name: hhsearch-configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/savra/HHsearch-config.git
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
server:
  port: 8447
encrypt:
  key: ${SECRET_KEY}