apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-fluent-bit-cm
  labels:
    app: {{ .Chart.Name }}
data:
  fluent-bit.conf: |-
    [SERVICE]
     Flush        1
     Daemon       Off
     Log_Level    Debug
     Parsers_File /fluent-bit/etc/parsers.conf

    [INPUT]
     Name         tail
     Mem_Buf_Limit 10MB
     Buffer_Chunk_Size 512k
     Buffer_Max_Size 512k
     Skip_Long_Lines On
     Path         /log/*.log
     Parser       custom
     Tag          event

    [FILTER]
     Name record_modifier
     Match *
     Record pod ${POD_NAME}

    [OUTPUT]
     Name  es
     Match *
     Host {{ .Values.elasticsearch.host }}
     Port {{ .Values.elasticsearch.port }}
     Index mycollection-logs
     Type _doc
     Time_Key fluentbit_timestamp
     Suppress_Type_Name On
  parsers.conf: |-
    [PARSER]
     Name        custom
     Format      json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-log-cm
  labels:
    app: {{ .Chart.Name }}
data:
  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="15 seconds">
        <statusListener class="ch.qos.logback.core.status.NopStatusListener"/>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>
                    %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n
                </pattern>
            </encoder>
        </appender>

        <appender name="jsonFileAppender" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/log/SystemOut.log</file>
            <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                <fileNamePattern>{{ .Chart.Name }}.%d{yyyy-MM-dd}.log.gz</fileNamePattern>
                <maxHistory>7</maxHistory>
            </rollingPolicy>
        </appender>

        <root level="info">
            <appender-ref ref="STDOUT"/>
            <appender-ref ref="jsonFileAppender"/>
        </root>
    </configuration>