spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    user: ${DATASOURCE_USERNAME}
    baseline-on-migrate: true
    table: hh_schema_history
    locations: classpath:db/migration/V1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: TRACE
    com.hvdbs.hhsearch: TRACE
  logback:
    rollingpolicy:
      max-history: 20
      max-file-size: 100KB
      file-name-pattern: hhsearch-%d{yyyy-MM-dd}.%i.log.gz
      total-size-cap: 2MB
  file:
    name: /log/SystemOut.log
#    reactor.netty.http.client: DEBUG

hhsearch:
  user-agent: HHsearch/1.0 (savra.sv@yandex.ru)
---
spring:
  config:
    activate:
      on-profile: prod